language: node_js  #设置语言

node_js: stable  #设置相应的版本

# cache: # 设置缓存
#   directories:
#   - blog/node_modules

before_install:
  - npm install hexo-cli@1.1.0 -g
  - export PATH="$HOME/.nvm/versions/node/$(node -v)/bin:$PATH"
  - echo $PATH
  - which hexo
  - hexo -v
  - hexo init blog
  - npm install  #安装hexo及插件
  - npm install hexo --save
  - npm install hexo-generator-sitemap
  - npm install hexo-generator-baidu-sitemap

  # - mv blog/node_modules node_modules
  # - rm -rf blog
  # - mkdir -p blog
  # - hexo init blog
  - cd blog
  - mkdir -p source/about
  - mkdir -p source/categories
  - mkdir -p source/tags
  - git clone https://github.com/GeekerHua/jacman themes/jacman
  # - mv ../node_modules node_modules

install:
  - npm install https://github.com/GeekerHua/hexo-asset-image.git

script:
  # - rm -rf source/_posts
  # - ./node_modules/.bin/hexo generate
  - cp -r ../_posts ./source/_posts
  - cp -f ../hexo/_config.yml _config.yml
  - cp ../hexo/about.md ./source/about/index.md
  - cp ../hexo/categories.md ./source/categories/index.md
  - cp ../hexo/tags.md ./source/tags/index.md
  - cp ../hexo/404.html ./source/404.html
  - echo "${BAIDU_VERIFY}" > ./source/baidu_verify_${BAIDU_VERIFY}.html
  - echo "google-site-verification:${GOOGLE_VERIFY}.html" > ./source/${GOOGLE_VERIFY}.html
  - echo "${CNAME}" > ./source/CNAME

after_script:
  - hexo generate
  - cp ../README.md ./public/README.md
  - cd ./public
  - git init
  - git config user.name "travis"  #修改name
  - git config user.email "travis@geekerhua.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称, 上传到github
  - git push --force --quiet "https://${CODING_USER}:${CODING_TOKEN}@${CODING_REF}" master:master # 上传到tencent

branches:
  only:
    - note  #只监测note分支
